using src.LibraryManagement;
Library library=new Library();
var comicBook = new Comic(1, "Comic Title", "Comic Author", new DateOnly(2022, 1, 1), true, true,"Hiba Ejaz",library);
var comicBook2 = new Comic(2, "Comic Title 2", "Comic Author 2", new DateOnly(2023, 6, 1), true, true,"Mama",library);
Librarian librarian=new Librarian("Mr Chips",1,library);
librarian.AddBook(comicBook);
librarian.AddBook(comicBook2);
var textBook = new TextBook(1, "text Title 2", "text Author 2", new DateOnly(2023, 1, 1), true, true);
librarian.AddBook(textBook);
//librarian.RemoveBook(comicBook);
Customer customer1=new Customer("hiba",06,library);
Customer customer2=new Customer("papa",0431,library);
customer1.BorrowBook(comicBook2);
customer2.BorrowBook(comicBook2);
customer1.ReturnBook(comicBook2);
customer2.BorrowBook(comicBook2);
customer1.ReturnBook(comicBook);
librarian.EditBook(comicBook,1, "Comic Edited Title", "Comic Author", new DateOnly(2022, 1, 1),"Fatima");
